// Mocks generated by Mockito 5.4.6 from annotations
// in pocketbase_sync/test/pb_sync_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:http/http.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;
import 'package:pocketbase/src/auth_store.dart' as _i2;
import 'package:pocketbase/src/client.dart' as _i15;
import 'package:pocketbase/src/dtos/auth_methods_list.dart' as _i17;
import 'package:pocketbase/src/dtos/jsonable.dart' as _i20;
import 'package:pocketbase/src/dtos/otp_response.dart' as _i19;
import 'package:pocketbase/src/dtos/record_auth.dart' as _i18;
import 'package:pocketbase/src/dtos/record_model.dart' as _i16;
import 'package:pocketbase/src/dtos/result_list.dart' as _i21;
import 'package:pocketbase/src/services/backup_service.dart' as _i10;
import 'package:pocketbase/src/services/batch_service.dart' as _i13;
import 'package:pocketbase/src/services/collection_service.dart' as _i4;
import 'package:pocketbase/src/services/cron_service.dart' as _i11;
import 'package:pocketbase/src/services/file_service.dart' as _i5;
import 'package:pocketbase/src/services/health_service.dart' as _i9;
import 'package:pocketbase/src/services/log_service.dart' as _i8;
import 'package:pocketbase/src/services/realtime_service.dart' as _i6;
import 'package:pocketbase/src/services/record_service.dart' as _i3;
import 'package:pocketbase/src/services/settings_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthStore_0 extends _i1.SmartFake implements _i2.AuthStore {
  _FakeAuthStore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordService_1 extends _i1.SmartFake implements _i3.RecordService {
  _FakeRecordService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionService_2 extends _i1.SmartFake
    implements _i4.CollectionService {
  _FakeCollectionService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileService_3 extends _i1.SmartFake implements _i5.FileService {
  _FakeFileService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeService_4 extends _i1.SmartFake
    implements _i6.RealtimeService {
  _FakeRealtimeService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsService_5 extends _i1.SmartFake
    implements _i7.SettingsService {
  _FakeSettingsService_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogService_6 extends _i1.SmartFake implements _i8.LogService {
  _FakeLogService_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHealthService_7 extends _i1.SmartFake implements _i9.HealthService {
  _FakeHealthService_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackupService_8 extends _i1.SmartFake implements _i10.BackupService {
  _FakeBackupService_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCronService_9 extends _i1.SmartFake implements _i11.CronService {
  _FakeCronService_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_10 extends _i1.SmartFake implements _i12.Client {
  _FakeClient_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_11 extends _i1.SmartFake implements Uri {
  _FakeUri_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchService_12 extends _i1.SmartFake implements _i13.BatchService {
  _FakeBatchService_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_13<T1> extends _i1.SmartFake implements _i14.Future<T1> {
  _FakeFuture_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePocketBase_14 extends _i1.SmartFake implements _i15.PocketBase {
  _FakePocketBase_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordModel_15 extends _i1.SmartFake implements _i16.RecordModel {
  _FakeRecordModel_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthMethodsList_16 extends _i1.SmartFake
    implements _i17.AuthMethodsList {
  _FakeAuthMethodsList_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordAuth_17 extends _i1.SmartFake implements _i18.RecordAuth {
  _FakeRecordAuth_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOTPResponse_18 extends _i1.SmartFake implements _i19.OTPResponse {
  _FakeOTPResponse_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResultList_19<M extends _i20.Jsonable> extends _i1.SmartFake
    implements _i21.ResultList<M> {
  _FakeResultList_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PocketBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPocketBase extends _i1.Mock implements _i15.PocketBase {
  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
        returnValueForMissingStub: _i22.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get baseURL => (super.noSuchMethod(
        Invocation.getter(#baseURL),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#baseURL),
        ),
        returnValueForMissingStub: _i22.dummyValue<String>(
          this,
          Invocation.getter(#baseURL),
        ),
      ) as String);

  @override
  String get lang => (super.noSuchMethod(
        Invocation.getter(#lang),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#lang),
        ),
        returnValueForMissingStub: _i22.dummyValue<String>(
          this,
          Invocation.getter(#lang),
        ),
      ) as String);

  @override
  _i2.AuthStore get authStore => (super.noSuchMethod(
        Invocation.getter(#authStore),
        returnValue: _FakeAuthStore_0(
          this,
          Invocation.getter(#authStore),
        ),
        returnValueForMissingStub: _FakeAuthStore_0(
          this,
          Invocation.getter(#authStore),
        ),
      ) as _i2.AuthStore);

  @override
  _i3.RecordService get admins => (super.noSuchMethod(
        Invocation.getter(#admins),
        returnValue: _FakeRecordService_1(
          this,
          Invocation.getter(#admins),
        ),
        returnValueForMissingStub: _FakeRecordService_1(
          this,
          Invocation.getter(#admins),
        ),
      ) as _i3.RecordService);

  @override
  _i4.CollectionService get collections => (super.noSuchMethod(
        Invocation.getter(#collections),
        returnValue: _FakeCollectionService_2(
          this,
          Invocation.getter(#collections),
        ),
        returnValueForMissingStub: _FakeCollectionService_2(
          this,
          Invocation.getter(#collections),
        ),
      ) as _i4.CollectionService);

  @override
  _i5.FileService get files => (super.noSuchMethod(
        Invocation.getter(#files),
        returnValue: _FakeFileService_3(
          this,
          Invocation.getter(#files),
        ),
        returnValueForMissingStub: _FakeFileService_3(
          this,
          Invocation.getter(#files),
        ),
      ) as _i5.FileService);

  @override
  _i6.RealtimeService get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeService_4(
          this,
          Invocation.getter(#realtime),
        ),
        returnValueForMissingStub: _FakeRealtimeService_4(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i6.RealtimeService);

  @override
  _i7.SettingsService get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeSettingsService_5(
          this,
          Invocation.getter(#settings),
        ),
        returnValueForMissingStub: _FakeSettingsService_5(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i7.SettingsService);

  @override
  _i8.LogService get logs => (super.noSuchMethod(
        Invocation.getter(#logs),
        returnValue: _FakeLogService_6(
          this,
          Invocation.getter(#logs),
        ),
        returnValueForMissingStub: _FakeLogService_6(
          this,
          Invocation.getter(#logs),
        ),
      ) as _i8.LogService);

  @override
  _i9.HealthService get health => (super.noSuchMethod(
        Invocation.getter(#health),
        returnValue: _FakeHealthService_7(
          this,
          Invocation.getter(#health),
        ),
        returnValueForMissingStub: _FakeHealthService_7(
          this,
          Invocation.getter(#health),
        ),
      ) as _i9.HealthService);

  @override
  _i10.BackupService get backups => (super.noSuchMethod(
        Invocation.getter(#backups),
        returnValue: _FakeBackupService_8(
          this,
          Invocation.getter(#backups),
        ),
        returnValueForMissingStub: _FakeBackupService_8(
          this,
          Invocation.getter(#backups),
        ),
      ) as _i10.BackupService);

  @override
  _i11.CronService get crons => (super.noSuchMethod(
        Invocation.getter(#crons),
        returnValue: _FakeCronService_9(
          this,
          Invocation.getter(#crons),
        ),
        returnValueForMissingStub: _FakeCronService_9(
          this,
          Invocation.getter(#crons),
        ),
      ) as _i11.CronService);

  @override
  _i12.Client Function() get httpClientFactory => (super.noSuchMethod(
        Invocation.getter(#httpClientFactory),
        returnValue: () => _FakeClient_10(
          this,
          Invocation.getter(#httpClientFactory),
        ),
        returnValueForMissingStub: () => _FakeClient_10(
          this,
          Invocation.getter(#httpClientFactory),
        ),
      ) as _i12.Client Function());

  @override
  set baseUrl(String? v) => super.noSuchMethod(
        Invocation.setter(
          #baseUrl,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set baseURL(String? value) => super.noSuchMethod(
        Invocation.setter(
          #baseURL,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lang(String? value) => super.noSuchMethod(
        Invocation.setter(
          #lang,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authStore(_i2.AuthStore? value) => super.noSuchMethod(
        Invocation.setter(
          #authStore,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set collections(_i4.CollectionService? value) => super.noSuchMethod(
        Invocation.setter(
          #collections,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set files(_i5.FileService? value) => super.noSuchMethod(
        Invocation.setter(
          #files,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set realtime(_i6.RealtimeService? value) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set settings(_i7.SettingsService? value) => super.noSuchMethod(
        Invocation.setter(
          #settings,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set logs(_i8.LogService? value) => super.noSuchMethod(
        Invocation.setter(
          #logs,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set health(_i9.HealthService? value) => super.noSuchMethod(
        Invocation.setter(
          #health,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set backups(_i10.BackupService? value) => super.noSuchMethod(
        Invocation.setter(
          #backups,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set crons(_i11.CronService? value) => super.noSuchMethod(
        Invocation.setter(
          #crons,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set httpClientFactory(_i12.Client Function()? value) => super.noSuchMethod(
        Invocation.setter(
          #httpClientFactory,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.RecordService collection(String? collectionIdOrName) =>
      (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionIdOrName],
        ),
        returnValue: _FakeRecordService_1(
          this,
          Invocation.method(
            #collection,
            [collectionIdOrName],
          ),
        ),
        returnValueForMissingStub: _FakeRecordService_1(
          this,
          Invocation.method(
            #collection,
            [collectionIdOrName],
          ),
        ),
      ) as _i3.RecordService);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String filter(
    String? expr, [
    Map<String, dynamic>? query = const {},
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #filter,
          [
            expr,
            query,
          ],
        ),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.method(
            #filter,
            [
              expr,
              query,
            ],
          ),
        ),
        returnValueForMissingStub: _i22.dummyValue<String>(
          this,
          Invocation.method(
            #filter,
            [
              expr,
              query,
            ],
          ),
        ),
      ) as String);

  @override
  Uri getFileUrl(
    _i16.RecordModel? record,
    String? filename, {
    String? thumb,
    String? token,
    Map<String, dynamic>? query = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileUrl,
          [
            record,
            filename,
          ],
          {
            #thumb: thumb,
            #token: token,
            #query: query,
          },
        ),
        returnValue: _FakeUri_11(
          this,
          Invocation.method(
            #getFileUrl,
            [
              record,
              filename,
            ],
            {
              #thumb: thumb,
              #token: token,
              #query: query,
            },
          ),
        ),
        returnValueForMissingStub: _FakeUri_11(
          this,
          Invocation.method(
            #getFileUrl,
            [
              record,
              filename,
            ],
            {
              #thumb: thumb,
              #token: token,
              #query: query,
            },
          ),
        ),
      ) as Uri);

  @override
  Uri buildUrl(
    String? path, [
    Map<String, dynamic>? queryParameters = const {},
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUrl,
          [
            path,
            queryParameters,
          ],
        ),
        returnValue: _FakeUri_11(
          this,
          Invocation.method(
            #buildUrl,
            [
              path,
              queryParameters,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeUri_11(
          this,
          Invocation.method(
            #buildUrl,
            [
              path,
              queryParameters,
            ],
          ),
        ),
      ) as Uri);

  @override
  Uri buildURL(
    String? path, [
    Map<String, dynamic>? queryParameters = const {},
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildURL,
          [
            path,
            queryParameters,
          ],
        ),
        returnValue: _FakeUri_11(
          this,
          Invocation.method(
            #buildURL,
            [
              path,
              queryParameters,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeUri_11(
          this,
          Invocation.method(
            #buildURL,
            [
              path,
              queryParameters,
            ],
          ),
        ),
      ) as Uri);

  @override
  _i13.BatchService createBatch() => (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [],
        ),
        returnValue: _FakeBatchService_12(
          this,
          Invocation.method(
            #createBatch,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeBatchService_12(
          this,
          Invocation.method(
            #createBatch,
            [],
          ),
        ),
      ) as _i13.BatchService);

  @override
  _i14.Future<T> send<T extends dynamic>(
    String? path, {
    String? method = 'GET',
    Map<String, String>? headers = const {},
    Map<String, dynamic>? query = const {},
    Map<String, dynamic>? body = const {},
    List<_i12.MultipartFile>? files = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [path],
          {
            #method: method,
            #headers: headers,
            #query: query,
            #body: body,
            #files: files,
          },
        ),
        returnValue: _i22.ifNotNull(
              _i22.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #send,
                  [path],
                  {
                    #method: method,
                    #headers: headers,
                    #query: query,
                    #body: body,
                    #files: files,
                  },
                ),
              ),
              (T v) => _i14.Future<T>.value(v),
            ) ??
            _FakeFuture_13<T>(
              this,
              Invocation.method(
                #send,
                [path],
                {
                  #method: method,
                  #headers: headers,
                  #query: query,
                  #body: body,
                  #files: files,
                },
              ),
            ),
        returnValueForMissingStub: _i22.ifNotNull(
              _i22.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #send,
                  [path],
                  {
                    #method: method,
                    #headers: headers,
                    #query: query,
                    #body: body,
                    #files: files,
                  },
                ),
              ),
              (T v) => _i14.Future<T>.value(v),
            ) ??
            _FakeFuture_13<T>(
              this,
              Invocation.method(
                #send,
                [path],
                {
                  #method: method,
                  #headers: headers,
                  #query: query,
                  #body: body,
                  #files: files,
                },
              ),
            ),
      ) as _i14.Future<T>);
}

/// A class which mocks [RecordService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordService extends _i1.Mock implements _i3.RecordService {
  @override
  String get baseCollectionPath => (super.noSuchMethod(
        Invocation.getter(#baseCollectionPath),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#baseCollectionPath),
        ),
        returnValueForMissingStub: _i22.dummyValue<String>(
          this,
          Invocation.getter(#baseCollectionPath),
        ),
      ) as String);

  @override
  String get baseCrudPath => (super.noSuchMethod(
        Invocation.getter(#baseCrudPath),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#baseCrudPath),
        ),
        returnValueForMissingStub: _i22.dummyValue<String>(
          this,
          Invocation.getter(#baseCrudPath),
        ),
      ) as String);

  @override
  _i15.PocketBase get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakePocketBase_14(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakePocketBase_14(
          this,
          Invocation.getter(#client),
        ),
      ) as _i15.PocketBase);

  @override
  _i16.RecordModel itemFactoryFunc(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #itemFactoryFunc,
          [json],
        ),
        returnValue: _FakeRecordModel_15(
          this,
          Invocation.method(
            #itemFactoryFunc,
            [json],
          ),
        ),
        returnValueForMissingStub: _FakeRecordModel_15(
          this,
          Invocation.method(
            #itemFactoryFunc,
            [json],
          ),
        ),
      ) as _i16.RecordModel);

  @override
  _i14.Future<_i6.UnsubscribeFunc> subscribe(
    String? topic,
    _i3.RecordSubscriptionFunc? callback, {
    String? expand,
    String? filter,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [
            topic,
            callback,
          ],
          {
            #expand: expand,
            #filter: filter,
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<_i6.UnsubscribeFunc>.value(
            () => _i14.Future<void>.value()),
        returnValueForMissingStub: _i14.Future<_i6.UnsubscribeFunc>.value(
            () => _i14.Future<void>.value()),
      ) as _i14.Future<_i6.UnsubscribeFunc>);

  @override
  _i14.Future<void> unsubscribe([String? topic = '']) => (super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [topic],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<_i16.RecordModel> update(
    String? id, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    List<_i12.MultipartFile>? files = const [],
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [id],
          {
            #body: body,
            #query: query,
            #files: files,
            #headers: headers,
            #expand: expand,
            #fields: fields,
          },
        ),
        returnValue: _i14.Future<_i16.RecordModel>.value(_FakeRecordModel_15(
          this,
          Invocation.method(
            #update,
            [id],
            {
              #body: body,
              #query: query,
              #files: files,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i16.RecordModel>.value(_FakeRecordModel_15(
          this,
          Invocation.method(
            #update,
            [id],
            {
              #body: body,
              #query: query,
              #files: files,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
      ) as _i14.Future<_i16.RecordModel>);

  @override
  _i14.Future<void> delete(
    String? id, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<_i17.AuthMethodsList> listAuthMethods({
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listAuthMethods,
          [],
          {
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue:
            _i14.Future<_i17.AuthMethodsList>.value(_FakeAuthMethodsList_16(
          this,
          Invocation.method(
            #listAuthMethods,
            [],
            {
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i17.AuthMethodsList>.value(_FakeAuthMethodsList_16(
          this,
          Invocation.method(
            #listAuthMethods,
            [],
            {
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i14.Future<_i17.AuthMethodsList>);

  @override
  _i14.Future<_i18.RecordAuth> authWithPassword(
    String? usernameOrEmail,
    String? password, {
    String? expand,
    String? fields,
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authWithPassword,
          [
            usernameOrEmail,
            password,
          ],
          {
            #expand: expand,
            #fields: fields,
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<_i18.RecordAuth>.value(_FakeRecordAuth_17(
          this,
          Invocation.method(
            #authWithPassword,
            [
              usernameOrEmail,
              password,
            ],
            {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i18.RecordAuth>.value(_FakeRecordAuth_17(
          this,
          Invocation.method(
            #authWithPassword,
            [
              usernameOrEmail,
              password,
            ],
            {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i14.Future<_i18.RecordAuth>);

  @override
  _i14.Future<_i18.RecordAuth> authWithOAuth2Code(
    String? provider,
    String? code,
    String? codeVerifier,
    String? redirectURL, {
    Map<String, dynamic>? createData = const {},
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authWithOAuth2Code,
          [
            provider,
            code,
            codeVerifier,
            redirectURL,
          ],
          {
            #createData: createData,
            #body: body,
            #query: query,
            #headers: headers,
            #expand: expand,
            #fields: fields,
          },
        ),
        returnValue: _i14.Future<_i18.RecordAuth>.value(_FakeRecordAuth_17(
          this,
          Invocation.method(
            #authWithOAuth2Code,
            [
              provider,
              code,
              codeVerifier,
              redirectURL,
            ],
            {
              #createData: createData,
              #body: body,
              #query: query,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i18.RecordAuth>.value(_FakeRecordAuth_17(
          this,
          Invocation.method(
            #authWithOAuth2Code,
            [
              provider,
              code,
              codeVerifier,
              redirectURL,
            ],
            {
              #createData: createData,
              #body: body,
              #query: query,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
      ) as _i14.Future<_i18.RecordAuth>);

  @override
  _i14.Future<_i18.RecordAuth> authWithOAuth2(
    String? providerName,
    _i3.OAuth2URLCallbackFunc? urlCallback, {
    List<String>? scopes = const [],
    Map<String, dynamic>? createData = const {},
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authWithOAuth2,
          [
            providerName,
            urlCallback,
          ],
          {
            #scopes: scopes,
            #createData: createData,
            #body: body,
            #query: query,
            #headers: headers,
            #expand: expand,
            #fields: fields,
          },
        ),
        returnValue: _i14.Future<_i18.RecordAuth>.value(_FakeRecordAuth_17(
          this,
          Invocation.method(
            #authWithOAuth2,
            [
              providerName,
              urlCallback,
            ],
            {
              #scopes: scopes,
              #createData: createData,
              #body: body,
              #query: query,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i18.RecordAuth>.value(_FakeRecordAuth_17(
          this,
          Invocation.method(
            #authWithOAuth2,
            [
              providerName,
              urlCallback,
            ],
            {
              #scopes: scopes,
              #createData: createData,
              #body: body,
              #query: query,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
      ) as _i14.Future<_i18.RecordAuth>);

  @override
  _i14.Future<_i18.RecordAuth> authRefresh({
    String? expand,
    String? fields,
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authRefresh,
          [],
          {
            #expand: expand,
            #fields: fields,
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<_i18.RecordAuth>.value(_FakeRecordAuth_17(
          this,
          Invocation.method(
            #authRefresh,
            [],
            {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i18.RecordAuth>.value(_FakeRecordAuth_17(
          this,
          Invocation.method(
            #authRefresh,
            [],
            {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i14.Future<_i18.RecordAuth>);

  @override
  _i14.Future<void> requestPasswordReset(
    String? email, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPasswordReset,
          [email],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> confirmPasswordReset(
    String? passwordResetToken,
    String? password,
    String? passwordConfirm, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPasswordReset,
          [
            passwordResetToken,
            password,
            passwordConfirm,
          ],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> requestVerification(
    String? email, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestVerification,
          [email],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> confirmVerification(
    String? verificationToken, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmVerification,
          [verificationToken],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> requestEmailChange(
    String? newEmail, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestEmailChange,
          [newEmail],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> confirmEmailChange(
    String? emailChangeToken,
    String? userPassword, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmEmailChange,
          [
            emailChangeToken,
            userPassword,
          ],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<_i19.OTPResponse> requestOTP(
    String? email, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestOTP,
          [email],
          {
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<_i19.OTPResponse>.value(_FakeOTPResponse_18(
          this,
          Invocation.method(
            #requestOTP,
            [email],
            {
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i19.OTPResponse>.value(_FakeOTPResponse_18(
          this,
          Invocation.method(
            #requestOTP,
            [email],
            {
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i14.Future<_i19.OTPResponse>);

  @override
  _i14.Future<_i18.RecordAuth> authWithOTP(
    String? otpId,
    String? password, {
    String? expand,
    String? fields,
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authWithOTP,
          [
            otpId,
            password,
          ],
          {
            #expand: expand,
            #fields: fields,
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<_i18.RecordAuth>.value(_FakeRecordAuth_17(
          this,
          Invocation.method(
            #authWithOTP,
            [
              otpId,
              password,
            ],
            {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i18.RecordAuth>.value(_FakeRecordAuth_17(
          this,
          Invocation.method(
            #authWithOTP,
            [
              otpId,
              password,
            ],
            {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i14.Future<_i18.RecordAuth>);

  @override
  _i14.Future<_i15.PocketBase> impersonate(
    String? recordId,
    num? duration, {
    String? expand,
    String? fields,
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #impersonate,
          [
            recordId,
            duration,
          ],
          {
            #expand: expand,
            #fields: fields,
            #body: body,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<_i15.PocketBase>.value(_FakePocketBase_14(
          this,
          Invocation.method(
            #impersonate,
            [
              recordId,
              duration,
            ],
            {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i15.PocketBase>.value(_FakePocketBase_14(
          this,
          Invocation.method(
            #impersonate,
            [
              recordId,
              duration,
            ],
            {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i14.Future<_i15.PocketBase>);

  @override
  _i14.Future<List<_i16.RecordModel>> getFullList({
    int? batch = 500,
    String? expand,
    String? filter,
    String? sort,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFullList,
          [],
          {
            #batch: batch,
            #expand: expand,
            #filter: filter,
            #sort: sort,
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue:
            _i14.Future<List<_i16.RecordModel>>.value(<_i16.RecordModel>[]),
        returnValueForMissingStub:
            _i14.Future<List<_i16.RecordModel>>.value(<_i16.RecordModel>[]),
      ) as _i14.Future<List<_i16.RecordModel>>);

  @override
  _i14.Future<_i21.ResultList<_i16.RecordModel>> getList({
    int? page = 1,
    int? perPage = 30,
    bool? skipTotal = false,
    String? expand,
    String? filter,
    String? sort,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getList,
          [],
          {
            #page: page,
            #perPage: perPage,
            #skipTotal: skipTotal,
            #expand: expand,
            #filter: filter,
            #sort: sort,
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<_i21.ResultList<_i16.RecordModel>>.value(
            _FakeResultList_19<_i16.RecordModel>(
          this,
          Invocation.method(
            #getList,
            [],
            {
              #page: page,
              #perPage: perPage,
              #skipTotal: skipTotal,
              #expand: expand,
              #filter: filter,
              #sort: sort,
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i21.ResultList<_i16.RecordModel>>.value(
                _FakeResultList_19<_i16.RecordModel>(
          this,
          Invocation.method(
            #getList,
            [],
            {
              #page: page,
              #perPage: perPage,
              #skipTotal: skipTotal,
              #expand: expand,
              #filter: filter,
              #sort: sort,
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i14.Future<_i21.ResultList<_i16.RecordModel>>);

  @override
  _i14.Future<_i16.RecordModel> getOne(
    String? id, {
    String? expand,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOne,
          [id],
          {
            #expand: expand,
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<_i16.RecordModel>.value(_FakeRecordModel_15(
          this,
          Invocation.method(
            #getOne,
            [id],
            {
              #expand: expand,
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i16.RecordModel>.value(_FakeRecordModel_15(
          this,
          Invocation.method(
            #getOne,
            [id],
            {
              #expand: expand,
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i14.Future<_i16.RecordModel>);

  @override
  _i14.Future<_i16.RecordModel> getFirstListItem(
    String? filter, {
    String? expand,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFirstListItem,
          [filter],
          {
            #expand: expand,
            #fields: fields,
            #query: query,
            #headers: headers,
          },
        ),
        returnValue: _i14.Future<_i16.RecordModel>.value(_FakeRecordModel_15(
          this,
          Invocation.method(
            #getFirstListItem,
            [filter],
            {
              #expand: expand,
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i16.RecordModel>.value(_FakeRecordModel_15(
          this,
          Invocation.method(
            #getFirstListItem,
            [filter],
            {
              #expand: expand,
              #fields: fields,
              #query: query,
              #headers: headers,
            },
          ),
        )),
      ) as _i14.Future<_i16.RecordModel>);

  @override
  _i14.Future<_i16.RecordModel> create({
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    List<_i12.MultipartFile>? files = const [],
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #body: body,
            #query: query,
            #files: files,
            #headers: headers,
            #expand: expand,
            #fields: fields,
          },
        ),
        returnValue: _i14.Future<_i16.RecordModel>.value(_FakeRecordModel_15(
          this,
          Invocation.method(
            #create,
            [],
            {
              #body: body,
              #query: query,
              #files: files,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i16.RecordModel>.value(_FakeRecordModel_15(
          this,
          Invocation.method(
            #create,
            [],
            {
              #body: body,
              #query: query,
              #files: files,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            },
          ),
        )),
      ) as _i14.Future<_i16.RecordModel>);
}
