// Mocks generated by Mockito 5.4.6 from annotations
// in pocketbase_sync/test/multi_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter/foundation.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:pocketbase/pocketbase.dart' as _i2;
import 'package:pocketbase_sync/repo/sync_repository.dart' as _i3;
import 'package:pocketbase_sync/sync/pb_sync_manager.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePocketBase_0 extends _i1.SmartFake implements _i2.PocketBase {
  _FakePocketBase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncRepository_1<T1> extends _i1.SmartFake
    implements _i3.SyncRepository<T1> {
  _FakeSyncRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueNotifier_3<T1> extends _i1.SmartFake
    implements _i4.ValueNotifier<T1> {
  _FakeValueNotifier_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PocketBaseSyncManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPocketBaseSyncManager<T> extends _i1.Mock
    implements _i5.PocketBaseSyncManager<T> {
  @override
  _i2.PocketBase get pb => (super.noSuchMethod(
        Invocation.getter(#pb),
        returnValue: _FakePocketBase_0(
          this,
          Invocation.getter(#pb),
        ),
        returnValueForMissingStub: _FakePocketBase_0(
          this,
          Invocation.getter(#pb),
        ),
      ) as _i2.PocketBase);

  @override
  String get collection => (super.noSuchMethod(
        Invocation.getter(#collection),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#collection),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#collection),
        ),
      ) as String);

  @override
  _i3.SyncRepository<T> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSyncRepository_1<T>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeSyncRepository_1<T>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.SyncRepository<T>);

  @override
  Map<String, dynamic> Function(T) get toJson => (super.noSuchMethod(
        Invocation.getter(#toJson),
        returnValue: (T __p0) => <String, dynamic>{},
        returnValueForMissingStub: (T __p0) => <String, dynamic>{},
      ) as Map<String, dynamic> Function(T));

  @override
  T Function(Map<String, dynamic>) get fromJson => (super.noSuchMethod(
        Invocation.getter(#fromJson),
        returnValue: (Map<String, dynamic> __p0) => _i6.dummyValue<T>(
          this,
          Invocation.getter(#fromJson),
        ),
        returnValueForMissingStub: (Map<String, dynamic> __p0) =>
            _i6.dummyValue<T>(
          this,
          Invocation.getter(#fromJson),
        ),
      ) as T Function(Map<String, dynamic>));

  @override
  Duration get retentionPeriod => (super.noSuchMethod(
        Invocation.getter(#retentionPeriod),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#retentionPeriod),
        ),
        returnValueForMissingStub: _FakeDuration_2(
          this,
          Invocation.getter(#retentionPeriod),
        ),
      ) as Duration);

  @override
  String Function() get idGenerator => (super.noSuchMethod(
        Invocation.getter(#idGenerator),
        returnValue: () => _i6.dummyValue<String>(
          this,
          Invocation.getter(#idGenerator),
        ),
        returnValueForMissingStub: () => _i6.dummyValue<String>(
          this,
          Invocation.getter(#idGenerator),
        ),
      ) as String Function());

  @override
  _i4.ValueNotifier<bool> get isConnectedNotifier => (super.noSuchMethod(
        Invocation.getter(#isConnectedNotifier),
        returnValue: _FakeValueNotifier_3<bool>(
          this,
          Invocation.getter(#isConnectedNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_3<bool>(
          this,
          Invocation.getter(#isConnectedNotifier),
        ),
      ) as _i4.ValueNotifier<bool>);

  @override
  _i7.Stream<void> get onUpdate => (super.noSuchMethod(
        Invocation.getter(#onUpdate),
        returnValue: _i7.Stream<void>.empty(),
        returnValueForMissingStub: _i7.Stream<void>.empty(),
      ) as _i7.Stream<void>);

  @override
  set autoSyncInterval(Duration? value) => super.noSuchMethod(
        Invocation.setter(
          #autoSyncInterval,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
      ) as String);

  @override
  void startAutoSync(Duration? interval) => super.noSuchMethod(
        Invocation.method(
          #startAutoSync,
          [interval],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopAutoSync() => super.noSuchMethod(
        Invocation.method(
          #stopAutoSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> create(
    String? id,
    T? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            id,
            item,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> update(
    String? id,
    T? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            id,
            item,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sync() => (super.noSuchMethod(
        Invocation.method(
          #sync,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> subscribe() => (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> unsubscribe() => (super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
